// This file is auto-generated. Do not edit manually.

export interface SubscriptionInput {
  /** Trial period of the subscription in days. Overrides the plan's trial period if set. */
  trial_period_days?: number | null;
  /** Modify fee quantities for the subscription plans and fees. */
  items?: { fee_id: string; plan_id: string; quantity: number; }[];
  /** Billing cycle type of the subscription. */
  billing_cycle_type?: 'anniversary' | 'calendar';
  /** Plan ID associated with the subscription. */
  plan_id?: string;
  /** Payment method ID associated with the subscription. Required if collection_method is `automatic`. */
  payment_method_id?: string | null;
  /** Payment collection method for invoices generated by the subscription. */
  collection_method?: string;
}
