// This file is auto-generated. Do not edit manually.

export interface Subscription {
  /** Represents the object's type. */
  object?: 'subscription';
  /** ID of the object. */
  id?: string;
  /** Status of the subscription. */
  status?: 'draft' | 'pending' | 'trialing' | 'active' | 'paused' | 'canceled' | 'expired';
  /** Billingrails account ID associated with the subscription. */
  account_id?: string;
  /** Plan ID associated with the subscription. */
  plan_id?: string;
  /** Payment method ID associated with the subscription. */
  payment_method_id?: string;
  /** Currency of the subscription. */
  currency?: string;
  /** Billing cycle type of the subscription. */
  billing_cycle_type?: 'anniversary' | 'calendar';
  /** Payment collection method for invoices generated by the subscription. */
  collection_method?: string;
  /** Date the subscription is billed through. */
  billed_through?: string | null;
  /** Date the subscription was canceled. */
  canceled_at?: string | null;
  /** Start date of the current billing period. */
  current_period_start?: string | null;
  /** End date of the current billing period. */
  current_period_end?: string | null;
  /** First billing date of the subscription. */
  first_billing_at?: string | null;
  /** Previous billing date of the subscription. */
  previous_billing_at?: string | null;
  /** Date the subscription started. */
  started_at?: string;
  /** End date of the trial period. */
  trial_period_end?: string | null;
  /** Start date of the trial period. */
  trial_period_start?: string | null;
  /** Timestamp indicating when the object was created. */
  created_at?: string;
  /** List of items in the subscription. */
  items?: { fee_id: string; plan_id: string; quantity: number; }[];
}
