// This file is auto-generated. Do not edit manually.

export interface SubscriptionInput {
  /** Plan ID associated with the subscription. */
  plan_id?: string;
  /** Payment collection method for invoices generated by the subscription. */
  collection_method?: 'manual' | 'automatic';
  /** Proration mode for the subscription. */
  proration_mode?: 'none' | 'invoice_immediately' | 'invoice_later';
  /** Payment method ID associated with the subscription. Required if collection_method is `automatic`. */
  payment_method_id?: string | null;
  /** Billing cycle type of the subscription. */
  billing_cycle_type?: 'anniversary' | 'calendar';
  /** Modify fee quantities for the subscription plans and fees. */
  items?: { fee_id: string | null; plan_id: string | null; price_id: string | null; quantity: number; }[];
}
